export type NavPath =
  | ''
  | 'about'
  | 'album'
  | 'article'
  | 'change-password'
  | 'city-champion'
  | 'documents'
  | 'event'
  | 'game-archives'
  | 'image'
  | 'lifetime-achievement-awards'
  | 'login'
  | 'member'
  | 'members'
  | 'news'
  | 'photo-gallery'
  | 'schedule';
