version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo `date` Installing dependencies...
      - npm install
      - npm install -g @angular/cli@14.0.1
  build:
    commands:
      - echo `date` Building Angular project...
      - ng build
  post_build:
    commands:
      - echo `date` Updating files in the S3 bucket...
      - aws s3 sync dist/ s3://londonchessclub.ca --delete
