export enum NavPathTypes {
  HOME = '',
  ABOUT = 'about',
  MEMBERS = 'members',
  MEMBER = 'member',
  SCHEDULE = 'schedule',
  EVENT = 'event',
  NEWS = 'news',
  ARTICLE = 'article',
  CITY_CHAMPION = 'city-champion',
  PHOTO_GALLERY = 'photo-gallery',
  GAME_ARCHIVES = 'game-archives',
  DOCUMENTS = 'documents',
  LOGIN = 'login',
  LOGOUT = 'logout',
  CHANGE_PASSWORD = 'change-password',

  ADD = 'add',
  EDIT = 'edit',
  VIEW = 'view',
}
