export enum NavPathTypes {
  HOME = '',
  MEMBERS = 'members',
  MEMBER_ADD = 'member/add',
  MEMBER_EDIT = 'member/edit',
  SCHEDULE = 'schedule',
  EVENT_ADD = 'event/add',
  EVENT_EDIT = 'event/edit',
  NEWS = 'news',
  ARTICLE_ADD = 'article/add',
  ARTICLE_EDIT = 'article/edit',
  ARTICLE_VIEW = 'article/view',
  CITY_CHAMPION = 'city-champion',
  PHOTO_GALLERY = 'photo-gallery',
  ABOUT = 'about',
  LOGIN = 'login',
  LOGOUT = 'logout',
  CHANGE_PASSWORD = 'change-password',
}
