import type { Image, ModificationInfo } from '@app/models';
import { generateId } from '@app/utils/common/generate-id.util';

// TODO: Move to common images database & add remaining archived images from old site

const modificationInfo: ModificationInfo = {
  dateCreated: '2025-01-01T23:00:00',
  dateLastEdited: '2025-01-01T23:00:00',
  createdBy: 'Michal Wiraszka',
  lastEditedBy: 'Michal Wiraszka',
};

export const images: Image[] = [
  {
    filename: '2019-active-championship-winner-kevin.jpg',
    caption: '2019 Active Championship Winner - Kevin',
    albums: ['Archives'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2019-speed-championship-winner-tony.jpg',
    caption: '2019 Speed Championship Winner - Tony',
    albums: ['Archives'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-1.jpg',
    caption: '2022 Post-Pandemic Chess Boom 1',
    albums: ['2022 Post-Pandemic Chess Boom'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-2.jpg',
    caption: '2022 Post-Pandemic Chess Boom 2',
    albums: ['2022 Post-Pandemic Chess Boom'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-3.jpg',
    caption: '2022 Post-Pandemic Chess Boom 3',
    albums: ['2022 Post-Pandemic Chess Boom'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-4.jpg',
    caption: '2022 Post-Pandemic Chess Boom 4',
    albums: ['2022 Post-Pandemic Chess Boom'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-5.jpg',
    caption: '2022 Post-Pandemic Chess Boom 5',
    albums: ['2022 Post-Pandemic Chess Boom'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-6.jpg',
    caption: '2022 Post-Pandemic Chess Boom 6',
    albums: ['2022 Post-Pandemic Chess Boom'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-7.jpg',
    caption: '2022 Post-Pandemic Chess Boom 7',
    albums: ['2022 Post-Pandemic Chess Boom'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-1.jpg',
    caption: '2022 City Championship 1',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-2.jpg',
    caption: '2022 City Championship 2',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-3.jpg',
    caption: '2022 City Championship 3',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-4.jpg',
    caption: '2022 City Championship 4',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-5.jpg',
    caption: '2022 City Championship 5',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-6.jpg',
    caption: '2022 City Championship 6',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-7.jpg',
    caption: '2022 City Championship 7',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-8.jpg',
    caption: '2022 City Championship 8',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-9.jpg',
    caption: '2022 City Championship 9',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-10.jpg',
    caption: '2022 City Championship 10',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-city-championship-11.jpg',
    caption: '2022 City Championship 11',
    albums: ['2022 City Championship'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2022-dave-jackson-memorial-winners.jpg',
    caption: '2022 Dave Jackson Memorial Tournament - Winners',
    albums: ['2022 Dave Jackson Memorial Tournament'],
    coverForAlbum: '2022 Dave Jackson Memorial Tournament',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-active-championship-winner.jpg',
    caption: '2023 Active Championship - Winner',
    albums: ['2023 Active Championship'],
    coverForAlbum: '2023 Active Championship',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-canadian-open.jpg',
    caption: '2023 Canadian Open in Calgary',
    albums: ['2023 Canadian Open in Calgary'],
    coverForAlbum: '2023 Canadian Open in Calgary',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-dave-jackson-memorial-tournament-adam.jpg',
    caption: '2023 Dave Jackson Memorial Tournament - Adam',
    albums: ['2023 Dave Jackson Memorial Tournament'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-dave-jackson-memorial-tournament-steve.jpg',
    caption: '2023 Dave Jackson Memorial Tournament - Steve',
    albums: ['2023 Dave Jackson Memorial Tournament'],
    coverForAlbum: '2023 Dave Jackson Memorial Tournament',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-gladiators-of-the-chessboard-event.jpg',
    caption: '2023 Gladiators of the Chessboard Event',
    albums: ['2023 Gladiators of the Chessboard'],
    coverForAlbum: '2023 Gladiators of the Chessboard',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-lifetime-achievement-award-gerry.jpg',
    caption: '2023 Lifetime Achievement Award - Gerry',
    albums: ['2023 Lifetime Achievement Awards'],
    coverForAlbum: '2023 Lifetime Achievement Awards',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-lifetime-achievement-award-jim.jpg',
    caption: '2023 Lifetime Achievement Award - Jim',
    albums: ['2023 Lifetime Achievement Awards'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-lifetime-achievement-award-steve.jpg',
    caption: '2023 Lifetime Achievement Award - Steve',
    albums: ['2023 Lifetime Achievement Awards'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-london-vs-western-olympiad-1.jpg',
    caption: '2023 London vs. Western Olympiad',
    albums: ['2023 London vs. Western Olympiad'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-london-vs-western-olympiad-2.jpg',
    caption: '2023 London vs. Western Olympiad',
    albums: ['2023 London vs. Western Olympiad'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-london-vs-western-olympiad-3.jpg',
    caption: '2023 London vs. Western Olympiad',
    albums: ['2023 London vs. Western Olympiad'],
    coverForAlbum: '2023 London vs. Western Olympiad',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-summer-solstice-showdown-tournament.jpg',
    caption: '2023 Summer Solstice Showdown Tournament',
    albums: ['2023 Summer Solstice Showdown Tournament'],
    coverForAlbum: '2023 Summer Solstice Showdown Tournament',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-tandem-simul-1.jpg',
    caption: '2023 Tandem Simul 1',
    albums: ['2023 Tandem Simul'],
    coverForAlbum: '2023 Tandem Simul',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2023-tandem-simul-2.jpg',
    caption: '2023 Tandem Simul [2 of 2]',
    albums: ['2023 Tandem Simul'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-1-hugo-shailesh.png',
    caption: 'Round 1 - Hugo vs Shailesh',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-1-tyler-nirmal.jpeg',
    caption: 'Round 1 - Tyler vs Nirmal',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-2-mark-wyntie.png',
    caption: 'Round 2 - Mark vs Wyntie',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-2-shailesh-george.png',
    caption: 'Round 2 - Shailesh vs George',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-2-william-adam.png',
    caption: 'Round 2 - William vs Adam',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-3-carl-william.jpeg',
    caption: 'Round 3 - Carl vs William',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-4-annabelle-adam.png',
    caption: 'Round 4 - Annabelle vs Adam',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-4-william-tyler.jpeg',
    caption: 'Round 4 - Carl vs William',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-5-mike-arun.png',
    caption: 'Round 5 - Mike vs Arun',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-5-steve-madeline.jpeg',
    caption: 'Round 5 - Steve vs Madeline',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: "2025 Rook's Revenge Rapid Tournament",
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-6-bryan-madeline.jpeg',
    caption: 'Round 6 - Bryan vs Madeline',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: '2025-rooks-revenge-round-6-william-mark.jpeg',
    caption: 'Round 6 - William vs Mark',
    albums: ["2025 Rook's Revenge Rapid Tournament"],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: 'championship-final.jpg',
    caption: 'Championship Final',
    albums: ['Archives'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: 'outdoor-chess.jpg',
    caption: 'Chess in the park!',
    albums: ['Archives'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: 'steve-lecture.jpg',
    caption: 'Steve Demmery giving a lecture',
    albums: ['Archives'],
    coverForAlbum: null,
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: 'tandem-simul-steve-geoffrey.jpg',
    caption: 'Tandem Simul with Steve Demmery and Geoffrey Ruelland',
    albums: ['Tandem Simul with Steve Demmery and Geoffrey Ruelland'],
    coverForAlbum: 'Tandem Simul with Steve Demmery and Geoffrey Ruelland',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
  {
    filename: 'the-old-guard.jpg',
    caption: 'The old guard',
    albums: ['Archives'],
    coverForAlbum: 'Archives',
    articleAppearances: 0,
    modificationInfo,
    fileSize: 0,
    id: generateId(),
  },
];
