import type { Photo } from '@app/models';

// TODO: Move to common images database
export const photos: Photo[] = [
  {
    filename: '2019-active-championship-winner-kevin.jpg',
    name: '2019 Active Championship Winner - Kevin',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2019-speed-championship-winner-tony.jpg',
    name: '2019 Speed Championship Winner - Tony',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-1.jpg',
    name: 'Post-Pandemic Chess Boom [1 of 7]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-2.jpg',
    name: 'Post-Pandemic Chess Boom [2 of 7]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-3.jpg',
    name: 'Post-Pandemic Chess Boom [3 of 7]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-4.jpg',
    name: 'Post-Pandemic Chess Boom [4 of 7]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-5.jpg',
    name: 'Post-Pandemic Chess Boom [5 of 7]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-6.jpg',
    name: 'Post-Pandemic Chess Boom [6 of 7]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-7.jpg',
    name: 'Post-Pandemic Chess Boom [7 of 7]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-1.jpg',
    name: '2022 City Championship [1 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-2.jpg',
    name: '2022 City Championship [2 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-3.jpg',
    name: '2022 City Championship [3 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-4.jpg',
    name: '2022 City Championship [4 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-5.jpg',
    name: '2022 City Championship [5 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-6.jpg',
    name: '2022 City Championship [6 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-7.jpg',
    name: '2022 City Championship [7 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-8.jpg',
    name: '2022 City Championship [8 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-9.jpg',
    name: '2022 City Championship [9 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-10.jpg',
    name: '2022 City Championship [10 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-city-championship-11.jpg',
    name: '2022 City Championship [11 of 11]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2022-dave-jackson-memorial-winners.jpg',
    name: '2022 Dave Jackson Memorial - Winners',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-active-championship-winner.jpg',
    name: '2023 Active Championship - Winner',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-canadian-open.jpg',
    name: '2023 Canadian Open in Calgary',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-dave-jackson-memorial-tournament-adam.jpg',
    name: '2023 Dave Jackson Memorial Tournament - Adam',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-dave-jackson-memorial-tournament-steve.jpg',
    name: '2023 Dave Jackson Memorial Tournament - Steve',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-gladiators-of-the-chessboard-event.jpg',
    name: '2023 Gladiators of the Chessboard Event',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-lifetime-achievement-award-gerry.jpg',
    name: '2023 Lifetime Achievement Award - Gerry',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-lifetime-achievement-award-jim.jpg',
    name: '2023 Lifetime Achievement Award - Jim',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-lifetime-achievement-award-steve.jpg',
    name: '2023 Lifetime Achievement Award - Steve',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-london-vs-western-olympiad-1.jpg',
    name: '2023 London vs. Western Olympiad',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-london-vs-western-olympiad-2.jpg',
    name: '2023 London vs. Western Olympiad',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-london-vs-western-olympiad-3.jpg',
    name: '2023 London vs. Western Olympiad',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-summer-solstice-showdown-tournament.jpg',
    name: '2023 Summer Solstice Showdown Tournament',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-tandem-simul-1.jpg',
    name: '2023 Tandem Simul [1 of 2]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2023-tandem-simul-2.jpg',
    name: '2023 Tandem Simul [2 of 2]',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: '2025-rooks-revenge-round-1-hugo-shailesh.png',
    name: 'Round 1 - Hugo vs Shailesh',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-1-tyler-nirmal.jpeg',
    name: 'Round 1 - Tyler vs Nirmal',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-2-mark-wyntie.png',
    name: 'Round 2 - Mark vs Wyntie',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-2-shailesh-george.png',
    name: 'Round 2 - Shailesh vs George',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-2-william-adam.png',
    name: 'Round 2 - William vs Adam',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-3-carl-william.jpeg',
    name: 'Round 3 - Carl vs William',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-4-annabelle-adam.png',
    name: 'Round 4 - Annabelle vs Adam',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-4-william-tyler.jpeg',
    name: 'Round 4 - Carl vs William',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-5-mike-arun.png',
    name: 'Round 5 - Mike vs Arun',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: true,
  },
  {
    filename: '2025-rooks-revenge-round-5-steve-madeline.jpeg',
    name: 'Round 5 - Steve vs Madeline',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: true,
  },
  {
    filename: '2025-rooks-revenge-round-6-bryan-madeline.jpeg',
    name: 'Round 6 - Bryan vs Madeline',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: '2025-rooks-revenge-round-6-william-mark.jpeg',
    name: 'Round 6 - William vs Mark',
    albums: ["Rook's Revenge Rapid Tournament"],
    isFeatured: false,
  },
  {
    filename: 'championship-final.jpg',
    name: 'Championship Final',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: 'outdoor-chess.jpg',
    name: 'Chess in the park!',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: 'steve-lecture.jpg',
    name: 'Steve Demmery Lecture',
    albums: ['Archives'],
    isFeatured: false,
  },
  {
    filename: 'tandem-simul-steve-geoffrey.jpg',
    name: 'Tandem Simul with Steve Demmery and Geoffrey Ruelland',
    albums: ['Archives'],
    isFeatured: true,
  },
  {
    filename: 'the-old-guard.jpg',
    name: 'The old guard',
    albums: ['Archives'],
    isFeatured: true,
  },
];

export const featuredPhotos = photos.filter(photo => photo.isFeatured);
