export enum AppStoreFeatureTypes {
  HOME = 'home',
  MEMBER_LIST = 'member-list',
  MEMBER_EDITOR = 'member-editor',
  SCHEDULE = 'schedule',
  ARTICLE_LIST = 'article-list',
  ARTICLE_EDITOR = 'article-editor',
  LONDON_CHESS_CHAMPION = 'london-chess-champion',
  LESSONS = 'lessons',
  SUPPLIES = 'supplies',
  ABOUT = 'about',
  LOGIN = 'login',

  AUTH = 'auth',
  MODAL = 'modal',
  ALERT = 'alert',
  NAV = 'nav',
  TOASTER = 'toaster',
  IMAGE_OVERLAY = 'image-overlay',
}
